apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
      autoscaling:
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: my-deployment